#!/usr/bin/perl

$user  = getpwuid($<);

$dir="/home1/z00/budgets";
$budgets="$dir/budgets-services";
$access="$dir/budget-access";



%value = ();
%valid = ();
%pool  = ();

# read budget file
open (BUDGET, "<$budgets") || die "$! $budgets\n";
while(<BUDGET>){
    if(/([\w-]+):(-?\d+):([\w-]+)/){
            $value{$1}=$2;
            $pool{$1}=$3;

    }
}
close(BUDGET);
open (ACCESS, "<$access") || die "$! $access\n";
printf("=========================================\n");
printf("%20s %20s\n", "Budget", "Remaining kAUs");
printf("-----------------------------------------\n");
while(<ACCESS>){
    if(/([\w-]+):[\w-]+:[\w-]+:(\S+)/){
        $code=$1;
        $list=$2;
            foreach $u (split(',',$list)){
                if( $user eq $u ){
                    if( $value{$code} > 0 ){
                        $au = $value{$code}/10000000.0;
                        printf("%20s %20.3f\n", $code, $au);
                    }else{
                        printf("%20s %20s\n", $code, "No resources left");
                    }
                    $valid{$code}=$value{$code};
                }
            }
    }
}
printf("=========================================\n");
close(ACCESS); 

